# Sadly abandoned, this doesn't integrate well with Github in that we can't see build/test progress
# otherwise it would be the preferred option for windows builds
version: '#{build}'
branches:
  only:
  - appveyor
image: Visual Studio 2022
configuration: Release
platform: Any CPU
before_build:
- cmd: dotnet restore
build:
  project: NLC.Library.sln
  verbosity: minimal
