# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# no longer needed as we can do this in travis

# trigger:
# - master

# pool:
#   vmImage: 'ubuntu-latest'

# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#     dotnet restore
#     dotnet build -c Release
#     dotnet test -c Release
#   displayName: 'Run a multi-line script'
