 version: 2.1

 orbs:
  windows: circleci/windows@2.4

 jobs:
   test:
     description: 'Setup and run tests'
     executor: 
       name: windows/default     
     steps:
       - checkout
       - run: 
           name: 'Install dependencies'
           command: dotnet.exe restore
       - run:
            name: 'Run tests'
            command: dotnet test
   build:
     description: 'Build app'
     executor: 
       name: windows/default
     steps:
       - checkout
       - run:
           name: 'Build app'
           command: dotnet.exe build -c Release
 workflows:
   test_and_build:
     jobs:
       - test
       - build:
            requires:
              - test
